---
title: "ScoutPDF"
author: "Sean McGarry"
date: "`r Sys.Date()`"
output: pdf_document
---
## Libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(DT)
library(scales)
library(readr)
library(xtable)
library(tidyr)
library(ggpubr)
library(stringr)
```
## Data Management
```{r, echo = False}
setwd("~/Desktop/Wareham/Data")

csv <- read.csv("all_games.csv") 

# Replace "TwoSeamFastball" or "FourSeamFastball" with "Fastball"
df <- csv %>%
  mutate(TaggedPitchType = ifelse(TaggedPitchType %in% c("TwoSeamFastBall", "FourSeamFastBall"), 
                                  "Fastball", TaggedPitchType))

# Rename Murf Gray
df1 <- df %>%
  mutate(Batter = ifelse(Batter == "Gray, Triston", 
                                  "Gray, Murf", Batter))

# Remove rows where "TaggedPitchType" is "Other" or "Undefined
df2 <- df1 %>%
  filter(TaggedPitchType != "Other")
df3 <- df2 %>%
  filter(TaggedPitchType != "Undefined")

# Convert the date_column to Date format
df3$Date <- as.Date(df3$Date)

df4 <- df3 %>% 
  mutate(RelHeight = as.double(substr(RelHeight, 1, nchar(RelHeight))), 
         Balls = as.double(substr(Balls, 1, nchar(Balls))), 
         Strikes = as.double(substr(Strikes, 1, nchar(Strikes))))
BACON <- read.csv("xwOBAcon.csv")
df4$Count <- paste(df4$Balls, df4$Strikes, sep = "-")

# Checks and CSV adjustments
Checker <- df4 %>%
  mutate(HitCheck = case_when(PlayResult %in% c('Single', 'Double', 'Triple', 'HomeRun') ~ TRUE, TRUE ~ FALSE),
         FastballCheck = if_else(TaggedPitchType == "Fastball", T, F),
         SinkerCheck = if_else(TaggedPitchType == "Sinker", T, F),
         ChangeUpCheck = if_else(TaggedPitchType == "ChangeUp", T, F),
         CutterCheck = if_else(TaggedPitchType == "Cutter", T, F),
         SliderCheck = if_else(TaggedPitchType == "Slider", T, F),
         CurveballCheck = if_else(TaggedPitchType == "Curveball", T, F),
         SplitterCheck = if_else(TaggedPitchType == "Splitter", T, F),
         GBCheck = case_when(TaggedHitType %in% c('GroundBall') ~ TRUE, TRUE ~ FALSE),
         BattedBallCheck = case_when(TaggedHitType %in% c('GroundBall', 'LineDrive', 'FlyBall', 'Popup') ~ TRUE, TRUE ~ FALSE), 
         CSWCheck = case_when(PitchCall %in% c('StrikeSwinging','StrikeCalled') ~ TRUE, TRUE ~ FALSE),
         StrikeCheck = case_when(PitchCall %in% c('StrikeSwinging', 'FoulBall', 'InPlay','StrikeCalled') ~ TRUE, TRUE ~ FALSE),
         ZoneCheck = case_when(between(PlateLocHeight, 1.59, 3.41) & between(PlateLocSide, -1, 1) ~ TRUE, TRUE ~ FALSE),
         SweetSpotCheck = case_when(between(Angle, 10, 30) ~ TRUE, TRUE ~ FALSE),
         HardHitCheck = case_when(between(ExitSpeed, 95, 120) ~ TRUE, TRUE ~ FALSE),
         BarrelCheck = case_when(between(Angle, 10, 30)  & between(ExitSpeed, 95, 120) ~ TRUE, TRUE ~ FALSE),
         WhiffCheck = case_when(PitchCall %in% c('StrikeSwinging') ~ TRUE, TRUE ~ FALSE),
         SwingCheck = case_when(PitchCall %in% c('StrikeSwinging', 'InPlay','FoulBall') ~ TRUE, TRUE ~ FALSE),
         CalledStrikeCheck = case_when(PitchCall %in% c('StrikeCalled') ~ TRUE, TRUE ~ FALSE),
         BallCheck = case_when(PitchCall %in% c('BallCalled', 'HitByPitch') ~ TRUE, TRUE ~ FALSE),
         FoulCheck = case_when(PitchCall %in% c('FoulBall') ~ TRUE, TRUE ~ FALSE),
         SingleCheck = case_when(PlayResult %in% c('Single') ~ TRUE, TRUE ~ FALSE),
         DoubleCheck = case_when(PlayResult %in% c('Double') ~ TRUE, TRUE ~ FALSE),
         TripleCheck = case_when(PlayResult %in% c('Triple') ~ TRUE, TRUE ~ FALSE),
         HRCheck = case_when(PlayResult %in% c('HomeRun') ~ TRUE, TRUE ~ FALSE),
         SacCheck = case_when(PlayResult %in% c('Sacrifice') ~ TRUE, TRUE ~ FALSE),
         HBPCheck = case_when(PitchCall %in% c('HitByPitch') ~ TRUE, TRUE ~ FALSE),
         StrikeoutCheck = case_when(KorBB == c('Strikeout') ~ TRUE, TRUE ~ FALSE),
         WalkCheck = case_when(KorBB %in% c('Walk') ~ TRUE, TRUE ~ FALSE),
         BIPCheck = case_when(PlayResult %in% c('Undefined') ~ FALSE, TRUE ~ TRUE), 
         ErrorCheck = if_else(PlayResult %in% c('Error'), TRUE, FALSE),
         ABCheck = StrikeoutCheck + BIPCheck - SacCheck,
         PACheck = StrikeoutCheck + WalkCheck + HBPCheck + BIPCheck
         )

baconcsv <- Checker %>% 
  mutate(floorExitSpeed = floor(ExitSpeed),
         floorLaunchAngle = trunc(Angle),) %>% 
  left_join(BACON, by = c("floorExitSpeed" = "launch_speed", 
                          "floorLaunchAngle" = "launch_angle"))

final <- baconcsv %>%
  mutate(across("av_xwOBAcon", ~replace_na(., 0)),
         xwOBAvalues = av_xwOBAcon + WalkCheck * 0.83 + HBPCheck * 0.86 + StrikeoutCheck * 0)

final$Date <- as.Date(final$Date, "%Y-%m-%d")

final$GameType <- ifelse(final$Batter == "", "Bullpen", "Intersquad")

final$PitchCount <- 0
for (i in 1:nrow(final)) {final$PitchCount[i] <- sum(final$Pitcher[1:i] == final$Pitcher[i])}


lgAVG <- final %>%
      summarize(
        Pitches = n(),
        PA = sum(PACheck, na.rm = TRUE),
        AB = sum(ABCheck, na.rm = TRUE),
        H = sum(HitCheck, na.rm = TRUE),
        `1B` = sum(SingleCheck, na.rm = TRUE),
        `2B` = sum(DoubleCheck, na.rm = TRUE),
        `3B` = sum(TripleCheck, na.rm = TRUE),
        HR = sum(HRCheck, na.rm = TRUE),
        TB = `1B` + (`2B` * 2) + (`3B` * 3) + (HR * 4),
        SO = sum(StrikeoutCheck, na.rm = TRUE),
        BB = sum(WalkCheck, na.rm = TRUE),
        HBP = sum(HBPCheck, na.rm = TRUE),
        xwOBA = round(mean(xwOBAvalues[PACheck == TRUE], na.rm = TRUE), 3),
        `CSW%` = mean(CSWCheck, na.rm = TRUE),
        `Chase%` = mean(SwingCheck[ZoneCheck == FALSE], na.rm = TRUE),
        `Whiff%` = mean(WhiffCheck[SwingCheck == TRUE], na.rm = TRUE),
        Barrels = sum(BarrelCheck, na.rm = T),
        `Barrel%` = sum(BarrelCheck[PACheck == TRUE], na.rm = T) / PA,
        BBE = sum(BattedBallCheck, na.rm = TRUE),
        AvgEV = mean(ExitSpeed[BattedBallCheck == TRUE], na.rm = TRUE),
        AvgLA = mean(Angle[BattedBallCheck == TRUE], na.rm = TRUE),
        AVG = H / AB,
        OBP = (H + BB + HBP) / PA,
        SLG = TB / AB,
        OPS = OBP + SLG,
        PPA = Pitches/PA,
        HardHits = sum(HardHitCheck, na.rm = T),
        `HardHit%` = sum(HardHitCheck, na.rm = T)/BBE,
        MaxEV = max(ExitSpeed, na.rm = T)
      ) 

stats <- final %>%
      mutate(
        Pitches = n(),
        K = sum(StrikeoutCheck, na.rm = T),
        PA = sum(PACheck, na.rm = TRUE),
        AB = sum(ABCheck, na.rm = TRUE),
        H = sum(HitCheck, na.rm = TRUE),
        `1B` = sum(SingleCheck, na.rm = TRUE),
        `2B` = sum(DoubleCheck, na.rm = TRUE),
        `3B` = sum(TripleCheck, na.rm = TRUE),
        HR = sum(HRCheck, na.rm = TRUE),
        TB = `1B` + (`2B` * 2) + (`3B` * 3) + (HR * 4),
        SO = sum(StrikeoutCheck, na.rm = TRUE),
        BB = sum(WalkCheck, na.rm = TRUE),
        HBP = sum(HBPCheck, na.rm = TRUE),
        xwOBA = round(mean(xwOBAvalues[PACheck == TRUE], na.rm = TRUE), 3),
        `CSW%` = mean(CSWCheck, na.rm = TRUE),
        `Chase%` = mean(SwingCheck[ZoneCheck == FALSE], na.rm = TRUE),
        `Whiff%` = mean(WhiffCheck[SwingCheck == TRUE], na.rm = TRUE),
        Barrels = sum(BarrelCheck, na.rm = T),
        `Barrel%` = sum(BarrelCheck[PACheck == TRUE], na.rm = T) / PA,
        BBE = sum(BattedBallCheck, na.rm = TRUE),
        AvgEV = mean(ExitSpeed[BattedBallCheck == TRUE], na.rm = TRUE),
        AvgLA = mean(Angle[BattedBallCheck == TRUE], na.rm = TRUE),
        AVG = H / AB,
        OBP = (H + BB + HBP) / PA,
        SLG = TB / AB,
        OPS = OBP + SLG,
        HardHits = sum(HardHitCheck, na.rm = T),
        PPA = Pitches/PA,
        MaxEV = max(ExitSpeed, na.rm = T),
        `CSW%` = scales::percent(`CSW%`, accuracy = 0.1),
        `Chase%` = scales::percent(`Chase%`, accuracy = 0.1),
        `Whiff%` = scales::percent(`Whiff%`, accuracy = 0.1),
        `Barrel%` = scales::percent(`Barrel%`, accuracy = 0.1),
        xwOBA = sprintf("%.3f", xwOBA),
        AvgEV = sprintf("%.1f", AvgEV),
        AvgLA = sprintf("%.1f", AvgLA),
        AVG = sprintf("%.3f", AVG),
        OBP = sprintf("%.3f", OBP),
        MaxEV = sprintf("%.1f", MaxEV),
        SLG = sprintf("%.3f", SLG),
        OPS = sprintf("%.3f", OPS),
        PPA = round(PPA, 2)
      )


```

## Player

```{r}
hitter_name = "Putnam, Eli"
hits = first(filter(final, Batter == hitter_name)$BatterSide)

date = Sys.Date()

team_name = "Wareham"

hit_last_name <- str_trim(str_extract(hitter_name, "^[^,]+"))

filtered = filter(final, Batter == hitter_name)
```

## Tables

```{r}
basic <- filtered %>%
      group_by(Batter) %>%
      filter(Batter == hitter_name) %>%
      summarize(
        Pitches = n(),
        PA = sum(PACheck, na.rm = TRUE),
        AB = sum(ABCheck, na.rm = TRUE),
        H = sum(HitCheck, na.rm = TRUE),
        `1B` = sum(SingleCheck, na.rm = TRUE),
        `2B` = sum(DoubleCheck, na.rm = TRUE),
        `3B` = sum(TripleCheck, na.rm = TRUE),
        HR = sum(HRCheck, na.rm = TRUE),
        TB = `1B` + (`2B` * 2) + (`3B` * 3) + (HR * 4),
        SO = sum(StrikeoutCheck, na.rm = TRUE),
        BB = sum(WalkCheck, na.rm = TRUE),
        HBP = sum(HBPCheck, na.rm = TRUE),
        xwOBA = round(mean(xwOBAvalues[PACheck == TRUE], na.rm = TRUE), 3),
        `CSW%` = mean(CSWCheck, na.rm = TRUE),
        `Chase%` = mean(SwingCheck[ZoneCheck == FALSE], na.rm = TRUE),
        `Whiff%` = mean(WhiffCheck[SwingCheck == TRUE], na.rm = TRUE),
        Barrels = sum(BarrelCheck, na.rm = T),
        `Barrel%` = sum(BarrelCheck[PACheck == TRUE], na.rm = T) / PA,
        BBE = sum(BattedBallCheck, na.rm = TRUE),
        AvgEV = mean(ExitSpeed[BattedBallCheck == TRUE], na.rm = TRUE),
        AvgLA = mean(Angle[BattedBallCheck == TRUE], na.rm = TRUE),
        AVG = H / AB,
        OBP = (H + BB + HBP) / PA,
        SLG = TB / AB,
        OPS = OBP + SLG,
        HardHits = sum(HardHitCheck, na.rm = T),
        PPA = Pitches/PA,
        MaxEV = max(ExitSpeed, na.rm = T)
      ) %>%
      mutate(
        `CSW%` = scales::percent(`CSW%`, accuracy = 0.1),
        `Chase%` = scales::percent(`Chase%`, accuracy = 0.1),
        `Whiff%` = scales::percent(`Whiff%`, accuracy = 0.1),
        `Barrel%` = scales::percent(`Barrel%`, accuracy = 0.1),
        xwOBA = sprintf("%.3f", xwOBA),
        AvgEV = sprintf("%.1f", AvgEV),
        AvgLA = sprintf("%.1f", AvgLA),
        AVG = sprintf("%.3f", AVG),
        OBP = sprintf("%.3f", OBP),
        MaxEV = sprintf("%.1f", MaxEV),
        SLG = sprintf("%.3f", SLG),
        OPS = sprintf("%.3f", OPS),
        PPA = round(PPA, 2)
      ) %>%
      select(
        Batter, PA, AB, H, `1B`, `2B`, `3B`, HR, TB, SO, BB, HBP, AVG, OBP, SLG, OPS, PPA
    )

comp_to_lg <- filtered %>%
      group_by(Batter) %>%
      filter(Batter == hitter_name) %>%
      summarize(
        Pitches = n(),
        PA = sum(PACheck, na.rm = TRUE),
        AB = sum(ABCheck, na.rm = TRUE),
        H = sum(HitCheck, na.rm = TRUE),
        `1B` = sum(SingleCheck, na.rm = TRUE),
        `2B` = sum(DoubleCheck, na.rm = TRUE),
        `3B` = sum(TripleCheck, na.rm = TRUE),
        HR = sum(HRCheck, na.rm = TRUE),
        TB = `1B` + (`2B` * 2) + (`3B` * 3) + (HR * 4),
        SO = sum(StrikeoutCheck, na.rm = TRUE),
        BB = sum(WalkCheck, na.rm = TRUE),
        HBP = sum(HBPCheck, na.rm = TRUE),
        xwOBA = ((round(mean(xwOBAvalues[PACheck == TRUE], na.rm = TRUE), 3))/lgAVG$xwOBA) * 100,
        `CSW%` = ((mean(CSWCheck, na.rm = TRUE))/lgAVG$`CSW%`)*100,
        `Chase%` = ((mean(SwingCheck[ZoneCheck == FALSE], na.rm = TRUE))/as.numeric(lgAVG$`Chase%`))*100,
        `Whiff%` = ((mean(WhiffCheck[SwingCheck == TRUE], na.rm = TRUE))/lgAVG$`Whiff%`)*100,
        Barrels = sum(BarrelCheck, na.rm = T),
        `Barrel%` = ((sum(BarrelCheck[PACheck == TRUE], na.rm = T) / PA)/ lgAVG$`Barrel%`)*100,
        BBE = sum(BattedBallCheck, na.rm = TRUE),
        AvgEV = ((mean(ExitSpeed[BattedBallCheck == TRUE], na.rm = TRUE))/lgAVG$AvgEV)*100,
        AvgLA = mean(Angle[BattedBallCheck == TRUE], na.rm = TRUE),
        AVG = H / AB,
        OBP = (H + BB + HBP) / PA,
        SLG = TB / AB,
        PPA = ((Pitches/PA)/lgAVG$PPA) *100,
        `OPS+` = 100 * ((OBP/lgAVG$OBP) + (SLG/lgAVG$SLG)-1),
        HardHits = sum(HardHitCheck, na.rm = T),
       `HardHit%` = (sum(HardHitCheck, na.rm = T)/BBE)/lgAVG$`HardHit%` * 100
      ) %>%
      mutate(
        `Compared To League AVG` = "100 is League Average",
        `OPS+` = round(`OPS+`, 2), 
        xwOBA = round(`xwOBA`, 2), 
        AvgEV= round(`AvgEV`, 2), 
        `HardHit%`= round(`HardHit%`, 2), 
        `Barrel%`= round(`Barrel%`, 2), 
        `CSW%`= round(`CSW%`, 2), 
        `Chase%`= round(`Chase%`, 2), 
        `Whiff%` = round(`Whiff%`, 2),
        PPA = round(PPA, 2)
      ) %>%
      select(
        `Compared To League AVG`, `OPS+`, xwOBA, AvgEV, `HardHit%`, `Barrel%`, `CSW%`, `Chase%`, `Whiff%`, PPA
    )


basicL <- filtered %>%
      group_by(Batter) %>%
      filter(Batter == hitter_name, PitcherThrows == "Left") %>%
      summarize(
        Pitches = n(),
        PA = sum(PACheck, na.rm = TRUE),
        AB = sum(ABCheck, na.rm = TRUE),
        H = sum(HitCheck, na.rm = TRUE),
        `1B` = sum(SingleCheck, na.rm = TRUE),
        `2B` = sum(DoubleCheck, na.rm = TRUE),
        `3B` = sum(TripleCheck, na.rm = TRUE),
        HR = sum(HRCheck, na.rm = TRUE),
        TB = `1B` + (`2B` * 2) + (`3B` * 3) + (HR * 4),
        SO = sum(StrikeoutCheck, na.rm = TRUE),
        BB = sum(WalkCheck, na.rm = TRUE),
        HBP = sum(HBPCheck, na.rm = TRUE),
        xwOBA = round(mean(xwOBAvalues[PACheck == TRUE], na.rm = TRUE), 3),
        `CSW%` = mean(CSWCheck, na.rm = TRUE),
        `Chase%` = mean(SwingCheck[ZoneCheck == FALSE], na.rm = TRUE),
        `Whiff%` = mean(WhiffCheck[SwingCheck == TRUE], na.rm = TRUE),
        Barrels = sum(BarrelCheck, na.rm = T),
        `Barrel%` = sum(BarrelCheck[PACheck == TRUE], na.rm = T) / PA,
        BBE = sum(BattedBallCheck, na.rm = TRUE),
        AvgEV = mean(ExitSpeed[BattedBallCheck == TRUE], na.rm = TRUE),
        AvgLA = mean(Angle[BattedBallCheck == TRUE], na.rm = TRUE),
        AVG = H / AB,
        OBP = (H + BB + HBP) / PA,
        SLG = TB / AB,
        OPS = OBP + SLG,
        HardHits = sum(HardHitCheck, na.rm = T),
        PPA = Pitches/PA,
        MaxEV = max(ExitSpeed, na.rm = T)
      ) %>%
      mutate(
        `Pitcher Hand` = "Left",
        `CSW%` = scales::percent(`CSW%`, accuracy = 0.1),
        `Chase%` = scales::percent(`Chase%`, accuracy = 0.1),
        `Whiff%` = scales::percent(`Whiff%`, accuracy = 0.1),
        `Barrel%` = scales::percent(`Barrel%`, accuracy = 0.1),
        xwOBA = sprintf("%.3f", xwOBA),
        AvgEV = sprintf("%.1f", AvgEV),
        AvgLA = sprintf("%.1f", AvgLA),
        AVG = sprintf("%.3f", AVG),
        OBP = sprintf("%.3f", OBP),
        MaxEV = sprintf("%.1f", MaxEV),
        PPA = round(PPA, 2),
        SLG = sprintf("%.3f", SLG),
        OPS = sprintf("%.3f", OPS)
      ) %>%
      select(
        `Pitcher Hand`, PA, AB, H, `1B`, `2B`, `3B`, HR, TB, SO, BB, HBP, AVG, OBP, SLG, OPS, PPA
    )

basicR <- filtered %>%
      group_by(Batter) %>%
      filter(Batter == hitter_name, PitcherThrows == "Right") %>%
      summarize(
        Pitches = n(),
        PA = sum(PACheck, na.rm = TRUE),
        AB = sum(ABCheck, na.rm = TRUE),
        H = sum(HitCheck, na.rm = TRUE),
        `1B` = sum(SingleCheck, na.rm = TRUE),
        `2B` = sum(DoubleCheck, na.rm = TRUE),
        `3B` = sum(TripleCheck, na.rm = TRUE),
        HR = sum(HRCheck, na.rm = TRUE),
        TB = `1B` + (`2B` * 2) + (`3B` * 3) + (HR * 4),
        SO = sum(StrikeoutCheck, na.rm = TRUE),
        BB = sum(WalkCheck, na.rm = TRUE),
        HBP = sum(HBPCheck, na.rm = TRUE),
        xwOBA = round(mean(xwOBAvalues[PACheck == TRUE], na.rm = TRUE), 3),
        `CSW%` = mean(CSWCheck, na.rm = TRUE),
        `Chase%` = mean(SwingCheck[ZoneCheck == FALSE], na.rm = TRUE),
        `Whiff%` = mean(WhiffCheck[SwingCheck == TRUE], na.rm = TRUE),
        Barrels = sum(BarrelCheck, na.rm = T),
        `Barrel%` = sum(BarrelCheck[PACheck == TRUE], na.rm = T) / PA,
        BBE = sum(BattedBallCheck, na.rm = TRUE),
        AvgEV = mean(ExitSpeed[BattedBallCheck == TRUE], na.rm = TRUE),
        AvgLA = mean(Angle[BattedBallCheck == TRUE], na.rm = TRUE),
        AVG = H / AB,
        OBP = (H + BB + HBP) / PA,
        SLG = TB / AB,
        PPA = Pitches/PA,
        OPS = OBP + SLG,
        HardHits = sum(HardHitCheck, na.rm = T),
        MaxEV = max(ExitSpeed, na.rm = T)
      ) %>%
      mutate(
        `Pitcher Hand` = "Right",
        `CSW%` = scales::percent(`CSW%`, accuracy = 0.1),
        `Chase%` = scales::percent(`Chase%`, accuracy = 0.1),
        `Whiff%` = scales::percent(`Whiff%`, accuracy = 0.1),
        `Barrel%` = scales::percent(`Barrel%`, accuracy = 0.1),
        xwOBA = sprintf("%.3f", xwOBA),
        AvgEV = sprintf("%.1f", AvgEV),
        AvgLA = sprintf("%.1f", AvgLA),
        AVG = sprintf("%.3f", AVG),
        OBP = sprintf("%.3f", OBP),
        MaxEV = sprintf("%.1f", MaxEV),
        SLG = sprintf("%.3f", SLG),
        PPA = round(PPA, 2),
        OPS = sprintf("%.3f", OPS)
      ) %>%
      select(
        `Pitcher Hand`, PA, AB, H, `1B`, `2B`, `3B`, HR, TB, SO, BB, HBP, AVG, OBP, SLG, OPS, PPA
    )

barrels <- filtered %>%
      group_by(Batter) %>%
      filter(Batter == hitter_name) %>%
      summarize(
        Pitches = n(),
        PA = sum(PACheck, na.rm = TRUE),
        AB = sum(ABCheck, na.rm = TRUE),
        H = sum(HitCheck, na.rm = TRUE),
        `1B` = sum(SingleCheck, na.rm = TRUE),
        `2B` = sum(DoubleCheck, na.rm = TRUE),
        `3B` = sum(TripleCheck, na.rm = TRUE),
        HR = sum(HRCheck, na.rm = TRUE),
        TB = `1B` + (`2B` * 2) + (`3B` * 3) + (HR * 4),
        SO = sum(StrikeoutCheck, na.rm = TRUE),
        BB = sum(WalkCheck, na.rm = TRUE),
        HBP = sum(HBPCheck, na.rm = TRUE),
        xwOBA = round(mean(xwOBAvalues[PACheck == TRUE], na.rm = TRUE), 3),
        `CSW%` = mean(CSWCheck, na.rm = TRUE),
        `Chase%` = mean(SwingCheck[ZoneCheck == FALSE], na.rm = TRUE),
        `Whiff%` = mean(WhiffCheck[SwingCheck == TRUE], na.rm = TRUE),
        Barrels = sum(BarrelCheck, na.rm = T),
        `Barrel%` = sum(BarrelCheck[PACheck == TRUE], na.rm = T) / PA,
        BBE = sum(BattedBallCheck, na.rm = TRUE),
        AvgEV = mean(ExitSpeed[BattedBallCheck == TRUE], na.rm = TRUE),
        AvgLA = mean(Angle[BattedBallCheck == TRUE], na.rm = TRUE),
        AVG = H / AB,
        OBP = (H + BB + HBP) / PA,
        SLG = TB / AB,
        HardHits = sum(HardHitCheck, na.rm = T),
        `HardHit%` = sum(HardHitCheck, na.rm = T)/BBE,
        MaxEV = max(ExitSpeed, na.rm = T)
      ) %>%
      mutate(
        `CSW%` = scales::percent(`CSW%`, accuracy = 0.1),
        `Chase%` = scales::percent(`Chase%`, accuracy = 0.1),
        `Whiff%` = scales::percent(`Whiff%`, accuracy = 0.1),
        `Barrel%` = scales::percent(`Barrel%`, accuracy = 0.1),
        xwOBA = sprintf("%.3f", xwOBA),
        AvgEV = sprintf("%.1f", AvgEV),
        AvgLA = sprintf("%.1f", AvgLA),
        AVG = sprintf("%.3f", AVG),
        OBP = sprintf("%.3f", OBP),
        MaxEV = sprintf("%.1f", MaxEV),
        `HardHit%` = scales::percent(`HardHit%`, accuracy = 0.1),
        SLG = sprintf("%.3f", SLG)
      ) %>%
      select(
         xwOBA, AvgEV, MaxEV, AvgLA, HardHits,`HardHit%`, Barrels, `Barrel%`, `CSW%`, `Chase%`, `Whiff%`
    )

barrelsL <- filtered %>%
      group_by(Batter) %>%
      filter(Batter == hitter_name, PitcherThrows == "Left") %>%
      summarize(
        Pitches = n(),
        PA = sum(PACheck, na.rm = TRUE),
        AB = sum(ABCheck, na.rm = TRUE),
        H = sum(HitCheck, na.rm = TRUE),
        `1B` = sum(SingleCheck, na.rm = TRUE),
        `2B` = sum(DoubleCheck, na.rm = TRUE),
        `3B` = sum(TripleCheck, na.rm = TRUE),
        HR = sum(HRCheck, na.rm = TRUE),
        TB = `1B` + (`2B` * 2) + (`3B` * 3) + (HR * 4),
        SO = sum(StrikeoutCheck, na.rm = TRUE),
        BB = sum(WalkCheck, na.rm = TRUE),
        HBP = sum(HBPCheck, na.rm = TRUE),
        xwOBA = round(mean(xwOBAvalues[PACheck == TRUE], na.rm = TRUE), 3),
        `CSW%` = mean(CSWCheck, na.rm = TRUE),
        `Chase%` = mean(SwingCheck[ZoneCheck == FALSE], na.rm = TRUE),
        `Whiff%` = mean(WhiffCheck[SwingCheck == TRUE], na.rm = TRUE),
        Barrels = sum(BarrelCheck, na.rm = T),
        `Barrel%` = sum(BarrelCheck[PACheck == TRUE], na.rm = T) / PA,
        BBE = sum(BattedBallCheck, na.rm = TRUE),
        AvgEV = mean(ExitSpeed[BattedBallCheck == TRUE], na.rm = TRUE),
        AvgLA = mean(Angle[BattedBallCheck == TRUE], na.rm = TRUE),
        AVG = H / AB,
        OBP = (H + BB + HBP) / PA,
        SLG = TB / AB,
        HardHits = sum(HardHitCheck, na.rm = T),
        `HardHit%` = sum(HardHitCheck, na.rm = T)/BBE,
        MaxEV = max(ExitSpeed, na.rm = T)
      ) %>%
      mutate(
         `Pitcher Hand` = "Left",
        `CSW%` = scales::percent(`CSW%`, accuracy = 0.1),
        `Chase%` = scales::percent(`Chase%`, accuracy = 0.1),
        `Whiff%` = scales::percent(`Whiff%`, accuracy = 0.1),
        `Barrel%` = scales::percent(`Barrel%`, accuracy = 0.1),
        `HardHit%` = scales::percent(`HardHit%`, accuracy = 0.1),
        xwOBA = sprintf("%.3f", xwOBA),
        AvgEV = sprintf("%.1f", AvgEV),
        AvgLA = sprintf("%.1f", AvgLA),
        AVG = sprintf("%.3f", AVG),
        OBP = sprintf("%.3f", OBP),
        MaxEV = sprintf("%.1f", MaxEV),
        SLG = sprintf("%.3f", SLG)
      ) %>%
      select(
        `Pitcher Hand`, xwOBA, AvgEV, MaxEV, AvgLA, HardHits,`HardHit%`, Barrels, `Barrel%`, `CSW%`, `Chase%`, `Whiff%`
    )

  
barrelsR <- filtered %>%
      group_by(Batter) %>%
      filter(Batter == hitter_name, PitcherThrows == "Right") %>%
      summarize(
        Pitches = n(),
        PA = sum(PACheck, na.rm = TRUE),
        AB = sum(ABCheck, na.rm = TRUE),
        H = sum(HitCheck, na.rm = TRUE),
        `1B` = sum(SingleCheck, na.rm = TRUE),
        `2B` = sum(DoubleCheck, na.rm = TRUE),
        `3B` = sum(TripleCheck, na.rm = TRUE),
        HR = sum(HRCheck, na.rm = TRUE),
        TB = `1B` + (`2B` * 2) + (`3B` * 3) + (HR * 4),
        SO = sum(StrikeoutCheck, na.rm = TRUE),
        BB = sum(WalkCheck, na.rm = TRUE),
        HBP = sum(HBPCheck, na.rm = TRUE),
        xwOBA = round(mean(xwOBAvalues[PACheck == TRUE], na.rm = TRUE), 3),
        `CSW%` = mean(CSWCheck, na.rm = TRUE),
        `Chase%` = mean(SwingCheck[ZoneCheck == FALSE], na.rm = TRUE),
        `Whiff%` = mean(WhiffCheck[SwingCheck == TRUE], na.rm = TRUE),
        Barrels = sum(BarrelCheck, na.rm = T),
        `Barrel%` = sum(BarrelCheck[PACheck == TRUE], na.rm = T) / PA,
        BBE = sum(BattedBallCheck, na.rm = TRUE),
        AvgEV = mean(ExitSpeed[BattedBallCheck == TRUE], na.rm = TRUE),
        AvgLA = mean(Angle[BattedBallCheck == TRUE], na.rm = TRUE),
        AVG = H / AB,
        OBP = (H + BB + HBP) / PA,
        SLG = TB / AB,
        HardHits = sum(HardHitCheck, na.rm = T),
        `HardHit%` = sum(HardHitCheck, na.rm = T)/BBE,
        MaxEV = max(ExitSpeed, na.rm = T)
      ) %>%
      mutate(
        `Pitcher Hand` = "Right",
        `CSW%` = scales::percent(`CSW%`, accuracy = 0.1),
        `Chase%` = scales::percent(`Chase%`, accuracy = 0.1),
        `Whiff%` = scales::percent(`Whiff%`, accuracy = 0.1),
        `Barrel%` = scales::percent(`Barrel%`, accuracy = 0.1),
        `HardHit%` = scales::percent(`HardHit%`, accuracy = 0.1),
        xwOBA = sprintf("%.3f", xwOBA),
        AvgEV = sprintf("%.1f", AvgEV),
        AvgLA = sprintf("%.1f", AvgLA),
        AVG = sprintf("%.3f", AVG),
        OBP = sprintf("%.3f", OBP),
        MaxEV = sprintf("%.1f", MaxEV),
        SLG = sprintf("%.3f", SLG)
      ) %>%
      select(
        `Pitcher Hand`, xwOBA, AvgEV, MaxEV, AvgLA, HardHits, `HardHit%`, Barrels, `Barrel%`, `CSW%`, `Chase%`, `Whiff%`
    )

```
## Good/Bad Zone 

```{r}
# Create a new variable to indicate "weak" or "good"
weak <- filtered %>%
  filter(PitchCall == "StrikeSwinging" | (ExitSpeed < 75 & TaggedHitType != "Bunt")) %>%
  mutate(Category = "Bad")

good <- filtered %>%
  filter(ExitSpeed >= 90 & PitchCall == "InPlay" | PlayResult %in% c('Single', 'Double', 'Triple', 'HomeRun')) %>%
  mutate(Category = "Good")

neutral <- filtered %>%
  filter(PitchCall %in% c("FoulBallNotFieldable", "FoulBallFieldable") | (ExitSpeed >= 75 & ExitSpeed < 90)) %>%
  mutate(Category = "Neutral")

# Combine both datasets
combined <- bind_rows(weak, good)

# Plot the combined data
outcomes_plot = ggplot(data = combined, aes(x = PlateLocSide, y = PlateLocHeight, color = Category)) +
  labs(x = "Horizontal Location", y = "Vertical Location", color = "Category", title = "Location (All) From the Pitcher's Perspective", subtitle = "Good = Hits & EVs >= 90, Bad = EVs < 75  & swing and misses") +  
  geom_point(size = 3) +
  annotate("rect", xmin = -1, xmax = 1,
           ymin = 1.6, ymax = 3.4,
           fill= NA, color= "black", 
           alpha = .1) +
  scale_color_manual(values = c("Bad" = "red", "Good" = "darkgreen")) +
  ylim(1, 4) + xlim(-1.8, 1.8) + 
  theme_bw() + 
  theme(plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        legend.position = "bottom", legend.text = element_text(size = 12), 
        axis.title = element_text(size = 14)) +
  coord_fixed(1.5) 

#Hand is "Right", "Left"
```

## OPS Zone

```{r}
make_zone <- function(hitter){
    # Check if pitcher_hand is NULL and filter accordingly
    result <- stats %>%
      filter(Batter == hitter, 
             (PitchCall == "InPlay" | KorBB == "Strikeout"))
    
    # Define the breaks for the grid
    x_breaks <- seq(-1.05, 1.05, length.out = 4)
    y_breaks <- seq(1.6, 3.3, length.out = 4)
    
    # Create a grid of tiles
    tiles <- expand.grid(
      x = x_breaks[-length(x_breaks)] + diff(x_breaks) / 2,
      y = y_breaks[-length(y_breaks)] + diff(y_breaks) / 2
    )
    
    # Group the data by the zones and calculate OPS
    ops_by_zone <- result %>%
      mutate(
        x_bin = cut(-PlateLocSide, breaks = x_breaks, labels = FALSE, include.lowest = TRUE),
        y_bin = cut(PlateLocHeight, breaks = y_breaks, labels = FALSE, include.lowest = TRUE)
      ) %>%
      filter(!is.na(x_bin) & !is.na(y_bin)) %>%  # Remove NA bins
      group_by(x_bin, y_bin) %>%
      summarise(
        PA = n(),
        AB = sum(ABCheck, na.rm = TRUE),
        K = sum(StrikeoutCheck, na.rm = TRUE),
        BBE = sum(BattedBallCheck, na.rm = TRUE),
        H = sum(HitCheck, na.rm = TRUE),
        `1B` = sum(SingleCheck, na.rm = TRUE),
        `2B` = sum(DoubleCheck, na.rm = TRUE),
        `3B` = sum(TripleCheck, na.rm = TRUE),
        HR = sum(HRCheck, na.rm = TRUE),
        TB = `1B` + (`2B` * 2) + (`3B` * 3) + (HR * 4),
        BB = sum(WalkCheck, na.rm = TRUE),
        HBP = sum(HBPCheck, na.rm = TRUE),
        OBP = (H + BB + HBP) / PA,
        SLG = TB / AB,
        OPS = OBP + SLG,
        .groups = 'drop'
      )
    
    # Calculate the midpoint for each bin
    ops_by_zone <- ops_by_zone %>%
      mutate(
        x = (x_breaks[x_bin] + x_breaks[x_bin + 1]) / 2,
        y = (y_breaks[y_bin] + y_breaks[y_bin + 1]) / 2
      )
    
    # Merge the tile data with the OPS values
    tiles <- merge(tiles, ops_by_zone[, c("x", "y", "OPS")], by = c("x", "y"), all.x = TRUE)
    tiles$OPS[is.na(tiles$OPS)] <- 0  # Replace NA OPS with 0
    tiles$OPS <- round(tiles$OPS, 3)
    
    # Plot the heatmap with OPS values
    zone <- ggplot() +
      geom_tile(data = tiles, aes(x = x, y = y, fill = OPS), color = "black") +
      scale_fill_gradient2(low = "#3661ad", mid = "white", high = "#d82129", midpoint = mean(tiles$OPS, na.rm = TRUE), na.value = "white") +
      geom_point(data = result, aes(x = -PlateLocSide, y = PlateLocHeight), color = "gray", size = 1, alpha = 0.6) +
      geom_text(data = tiles, aes(x = x, y = y, label = OPS), color = "black") +
      geom_rect(xmin = -1.05, xmax = 1.05, ymin = 1.6, ymax = 3.3, fill = "transparent", color = "black") +
      ylim(0.75, 3.75) +
      xlim(-2, 2) +
      theme_classic() +
      xlab("") +
      ylab("") +
      labs(title = paste("OPS per Strike Zone Segment")) +
      theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
      coord_fixed(ratio = 1.3)

    return(zone)
}

```
## Spary Chart
```{r}
spray_chart <- function(df, hitter_name){
  # Function to create circle data within a specific angle range
  create_circle_data <- function(radius, start_angle = 45, end_angle = 135, center_x = 0, center_y = 0, n_points = 100) {
    theta <- seq(start_angle, end_angle, length.out = n_points) * pi / 180
    x <- center_x + radius * cos(theta)
    y <- center_y + radius * sin(theta)
    data.frame(x = x, y = y)
  }
  
  # Data cleaning and transformation
  df <- df %>%
    filter(!is.na(Distance) & !is.na(Bearing)) %>%
    mutate(swing = if_else(PitchCall %in% c('InPlay', 'StrikeSwinging', 'FoulBall'), 1, 0),
           whiff = if_else(PitchCall == 'StrikeSwinging', 1, 0),
           Count = paste(Balls, "-", Strikes),
           hc_x = sin(Bearing * pi / 180) * Distance,
           hc_y = cos(Bearing * pi / 180) * Distance)
  
  # Select all playable batted balls
  data <- df %>%
    filter(abs(Bearing) <= 55, Batter == hitter_name)
  
  # Create circle data for the outfield fence within 45 to 135 degrees
  circle_data <- create_circle_data(350)
  
  p <- ggplot(data, aes(x = hc_x, y = hc_y, color = ExitSpeed)) +
    geom_point(size = 2) +
    scale_color_gradient2(low = "blue", mid = "black", high = "red", midpoint = 60) +
    labs(title = paste('Spray Chart for', hitter_name), color = 'EV (mph)') +
    
    # Add baseball field components
    geom_path(data = data.frame(x = c(0, 90, 0, -90, 0), y = c(0, 90, 180, 90, 0)),
              aes(x = x, y = y), color = 'black') +
    
    geom_path(data = data.frame(x = c(0, -350 * cos(pi / 4)),
                                y = c(0, 350 * sin(pi / 4))), 
              aes(x = x, y = y), color = 'black') +
    geom_path(data = data.frame(x = c(0, 350 * cos(pi / 4)),
                                y = c(0, 350 * sin(pi / 4))), 
              aes(x = x, y = y), color = 'black') +
    
    geom_path(data = circle_data, aes(x = x, y = y), color = 'black') +
    
    coord_fixed(xlim = c(-400, 400), ylim = c(-400, 400)) +
    theme_void()

  
  return(p)
}
```
## Plot Output
```{r}
# Assuming summary_table, pitch_types_table, usage_table_side are data frames
barrels_grob <- tableGrob(barrels)
basic_grob <- tableGrob(basic)
basicL_grob <- tableGrob(basicL)
basicR_grob <- tableGrob(basicR)
barrelsL_grob <- tableGrob(barrelsL)
barrelsR_grob <- tableGrob(barrelsR)
comp_to_lg_grob <- tableGrob(comp_to_lg)
#usage_table_side_grob <- tableGrob(usage_table_side)
# Combine plots and tables
fig <- ggarrange(
  basic_grob,
  barrels_grob,
  comp_to_lg_grob,
  basicL_grob,
  basicR_grob,
  barrelsL_grob,
  barrelsR_grob,
  #outcomes_plot,
  #advanced_grob,
 # usage_table_side_grob,
  ncol = 1, nrow = 8
)

# Annotate the figure
ann_fig <- annotate_figure(
  fig, 
  top = text_grob(paste0(hitter_name, " - ", team_name, " - ", hits))
)

# Create the directory if it doesn't exist
dir.create(paste0("~/Desktop/Wareham/Scouting/", team_name, "/Hitters/Tables/", date), showWarnings = FALSE, recursive = TRUE)

# Create and open the PDF device
pdf(file = paste0("~/Desktop/Wareham/Scouting/", team_name, "/Hitters/Tables/",date,"/", hit_last_name, "_report.pdf"), width = 10, height = 6)

# Print the annotated figure to the PDF
print(ann_fig)
print(make_zone(hitter_name))
print(spray_chart(filtered, hitter_name))
# Close the PDF device
dev.off()
```


